// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeH7VP7kyr6IB50xTjb8LxYpCFmNTZiTg',
    appId: '1:477054082230:android:d8cd31e778cb8aa8079a17',
    messagingSenderId: '477054082230',
    projectId: 'invoice-daily-c6e50',
    storageBucket: 'invoice-daily-c6e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEiQwBVoNNMREg2Qc8CaQ6g5WjP6q8nLk',
    appId: '1:477054082230:ios:8d830991f74848ee079a17',
    messagingSenderId: '477054082230',
    projectId: 'invoice-daily-c6e50',
    storageBucket: 'invoice-daily-c6e50.firebasestorage.app',
    androidClientId:
        '477054082230-o7259bf31asjr2ls151bc8u8c9q4v4j9.apps.googleusercontent.com',
    iosClientId:
        '477054082230-degdbrjjru33ibqs9qejmqhkb1o7uad1.apps.googleusercontent.com',
    iosBundleId: 'com.invoicedaily.apptest',
  );
}
